player_list_hard = [
'Gabriel Batistuta',
'Hernan Crespo',
'Mario Kempes',
'Daniel Passarella',
'Javier Saviola',
'Omar Sivori',
'Juan Sebastian Veron',
'Jan Ceulemans',
'Jean Marie Pfaff',
'Franky Van der Elst',
'Carlos Alberto',
'Djalma Santos',
'Nilton Santos',
'Socrates',
'Zico',
'Hristo Stoichkov',
'Roger Milla',
'Elias Figueroa',
'Ivan Zamorano',
'Carlos Valderrama',
'Davor Suker',
'Josef Masopust',
'Pavel Nedved',
'Brian Laudrup',
'Michael Laudrup',
'Peter Schmeichel',
'Gordon Banks',
'Bobby Charlton',
'Kevin Keegan',
'Gary Lineker',
'Michael Owen',
'Alan Shearer',
'Eric Cantona',
'Marcel Desailly',
'Didier Deschamps',
'Just Fontaine',
'Raymond Kopa',
'Jean Pierre Papin',
'Robert Pires',
'Michel Platini',
'Lilian Thuram',
'Marius Tresor',
'David Trezeguet',
'Patrick Vieira',
'Michael Ballack',
'Franz Beckenbauer',
'Paul Breitner',
'Oliver Kahn',
'Jurgen Klinsmann',
'Sepp Maier',
'Lothar Matthaus',
'Gerd Muller',
'Karl Heinz Rummenigge',
'Uwe Seeler',
'Abedi Pele',
'Ferenc Puskas',
'Roberto Baggio',
'Franco Baresi',
'Giuseppe Bergomi',
'Giampiero Boniperti',
'Gianluigi Buffon',
'Alessandro Del Piero',
'Giacinto Facchetti',
'Paolo Maldini',
'Alessandro Nesta',
'Gianni Rivera',
'Paolo Rossi',
'Francesco Totti',
'Christian Vieri',
'Dino Zoff',
'Hidetoshi Nakata',
'George Weah',
'Marco van Basten',
'Dennis Bergkamp',
'Edgar Davids',
'Ruud Gullit',
'Rene van de Kerkhof',
'Willy van de Kerkhof',
'Patrick Kluivert',
'Johan Neeskens',
'Rob Rensenbrink',
'Frank Rijkaard',
'Clarence Seedorf',
'Jay Jay Okocha',
'George Best',
'Romerito',
'Teófilo Cubillas',
'Zbigniew Boniek',
'Roy Keane',
'Gheorghe Hagi',
'Rinat Dasayev',
'Kenny Dalglish',
'El Hadji Diouf',
'Hong Myung-bo',
'Emilio Butragueno',
'Rustu Recber',
'Emre Belozoglu',
'Andriy Shevchenko',
'Michelle Akers',
]

player_list_easy = [
'Leo Messi',
'Cristiano Ronaldo',
'Neymar',
'Mbappe',
'Ramos',
'Lewandoski',
'Salah',
'Ansu Fati',
'Diego Maradona',
'Cafu',
'Falcao',
'Pele',
'Junior',
'Rivaldo',
'Rivelino',
'Roberto Carlos',
'Romario',
'Ronaldinho',
'Ronaldo',
'David Beckham',
'Thierry Henry',
'Zinedine Zidane',
'Hugo Sanchez',
'Eusebio',
'Luis Figo',
'Luis Enrique',
'Raul',
'Luis Suarez',
'Kaka',
'Manuel Neuer',
'Xavi',
'Andres Iniesta',
'Gerard Pique',
'Steven Gerrard',
'Thomas Muller',
'Sergio Ramos',
'Ronaldo',
'Wayne Rooney',
'Luka Modric',
'Zlatan Ibrahimovic',
'Dani Alves',
'Karim Benzema',
'Sergio Aguero',
'Didier Drogba',
'Frank Ribery',
'Sergio Busquets',
'Gareth Bale',
'David Villa',
'Eden Hazard',
'Angel Di Maria',
'Virgil van Dijk',
'Radamel Falcao',
'Antoine Griezmann',
'Kevin de Bruyne',
'Carlos Puyol',
'Yaya Toure',
'John Terry',
'Toni Kroos',
'Ivan Rakitic',
'Harry Kane',
'NGolo Kante',
'Jan Oblak',
'David Silva',
'Raphael Varane',
'Raheem Sterling',
]

player_list_medium = [
'balloteli',
'Erikson',
'Alfredo Di Stefano',
'Javier Zanetti',
'Johan Cruyff',
'Ruud van Nistelrooy',
'Rui Costa',
'Ashley Cole',
'Arjen Robben',
'Philipp Lahm',
'Samuel Eto’o',
'Francesco Totti',
'Patrick Vieira',
'Frank Lampard',
'Claude Makelee',
'Andrea Pirlo',
'Rio Ferdinand',
'Andriy Shevchenko',
'Nemanja Vidic',
'Paul Scholes',
'Petr Cech',
'Pavel Nedved',
'Xabi Alonso',
'Vincent Kompany',
'Alexis Sanchez',
'Edinson Cavani',
'Alessandro Nesta',
'Wesley Sneijder',
'Cesc Fabregas',
'Fabio Cannavaro',
'Marcelo',
'Paolo Maldini',
'Trent Alexander-Arnold',
'David De Gea',
'Mesut Ozil',
'Carlos Tevez',
'Arturo Vidal',
'Thibaut Courtois',
'Thiago Silva',
'Juan Roman Riquelme',
'Fernando Torres',
'Henrik Larsson',
]
